# Generated by Django 4.0.5 on 2022-08-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_permanent_address_user_present_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_blood_donation_date',
            field=models.DateField(null=True),
        ),
    ]
